apiVersion: v1
kind: Service
metadata:
  name: {{ include "eos.fullname" . }}
  labels:
    {{- include "eos.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "eos.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 4000
      protocol: TCP
      name: http
