//! EOS IoT Agent — Example plugin: mock temperature & humidity sensor.
//!
//! Connects to the EOS agent via Phoenix Channels (JSON WebSocket transport),
//! registers as a WeatherObserved provider, and publishes mock readings every 10 s.
//!
//! Required env vars (injected by the EOS operator into the plugin pod):
//!   PLUGIN_ID          — unique plugin name, e.g. "temp-sensor-1"
//!   PLUGIN_TOKEN       — HMAC auth token generated by the operator
//!   IOT_AGENT_WS_URL   — WebSocket base URL, e.g. "ws://eos-agent:4000/plugins"

use std::{env, time::Duration};

use anyhow::{anyhow, Context, Result};
use futures_util::{SinkExt, StreamExt};
use rand::Rng;
use serde_json::{json, Value};
use tokio::time::{interval, sleep};
use tokio_tungstenite::{connect_async, tungstenite::Message};
use tracing::{debug, error, info, warn};
use uuid::Uuid;

// ---------------------------------------------------------------------------
// Phoenix channel wire format helpers
//
// Format: [join_ref, ref, topic, event, payload]
// ---------------------------------------------------------------------------

fn phx_msg(
    join_ref: Option<&str>,
    msg_ref: &str,
    topic: &str,
    event: &str,
    payload: Value,
) -> Message {
    Message::Text(json!([join_ref, msg_ref, topic, event, payload]).to_string().into())
}

fn next_ref() -> String {
    Uuid::new_v4().to_string()
}

// ---------------------------------------------------------------------------
// NGSI-LD entity builders
// ---------------------------------------------------------------------------

fn entity_id(plugin_id: &str) -> String {
    format!("urn:ngsi-ld:WeatherObserved:{plugin_id}")
}

fn build_entity(plugin_id: &str, temp: f64, humidity: f64) -> Value {
    json!({
        "id": entity_id(plugin_id),
        "type": "WeatherObserved",
        "@context": [
            "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld",
            "https://smartdatamodels.org/context.jsonld"
        ],
        "temperature": {
            "type": "Property",
            "value": temp,
            "unitCode": "CEL",
            "observedAt": now_iso8601()
        },
        "relativeHumidity": {
            "type": "Property",
            "value": humidity,
            "observedAt": now_iso8601()
        },
        "dateObserved": {
            "type": "Property",
            "value": {
                "@type": "DateTime",
                "@value": now_iso8601()
            }
        }
    })
}

fn build_update_attrs(temp: f64, humidity: f64) -> Value {
    json!({
        "temperature": {
            "type": "Property",
            "value": temp,
            "unitCode": "CEL",
            "observedAt": now_iso8601()
        },
        "relativeHumidity": {
            "type": "Property",
            "value": humidity,
            "observedAt": now_iso8601()
        },
        "dateObserved": {
            "type": "Property",
            "value": {
                "@type": "DateTime",
                "@value": now_iso8601()
            }
        }
    })
}

// ---------------------------------------------------------------------------
// ISO-8601 timestamp without external date crates
// ---------------------------------------------------------------------------

fn now_iso8601() -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    let secs = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();
    let (y, mo, d, h, mi, s) = unix_secs_to_parts(secs);
    format!("{y:04}-{mo:02}-{d:02}T{h:02}:{mi:02}:{s:02}Z")
}

/// Converts Unix epoch seconds to (year, month, day, hour, minute, second) UTC.
fn unix_secs_to_parts(mut secs: u64) -> (u64, u64, u64, u64, u64, u64) {
    let s = secs % 60; secs /= 60;
    let mi = secs % 60; secs /= 60;
    let h = secs % 24; secs /= 24;
    // Rata Die algorithm: days since Unix epoch → Gregorian date
    let z = secs + 719_468;
    let era = z / 146_097;
    let doe = z - era * 146_097;
    let yoe = (doe - doe / 1_460 + doe / 36_524 - doe / 146_096) / 365;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = doy - (153 * mp + 2) / 5 + 1;
    let mo = if mp < 10 { mp + 3 } else { mp - 9 };
    let y = if mo <= 2 { yoe + era * 400 + 1 } else { yoe + era * 400 };
    (y, mo, d, h, mi, s)
}

// ---------------------------------------------------------------------------
// Mock sensor with Gaussian-ish random walk
// ---------------------------------------------------------------------------

struct Sensor {
    temperature: f64,
    humidity: f64,
}

impl Sensor {
    fn new() -> Self {
        let mut rng = rand::thread_rng();
        Self {
            temperature: rng.gen_range(18.0..26.0),
            humidity: rng.gen_range(0.40..0.80),
        }
    }

    fn tick(&mut self) {
        let mut rng = rand::thread_rng();
        self.temperature = (self.temperature + rng.gen_range(-0.5_f64..0.5)).clamp(0.0, 50.0);
        self.humidity = (self.humidity + rng.gen_range(-0.02_f64..0.02)).clamp(0.0, 1.0);
    }

    fn temp(&self) -> f64 { (self.temperature * 100.0).round() / 100.0 }
    fn hum(&self)  -> f64 { (self.humidity  * 1000.0).round() / 1000.0 }
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

#[tokio::main]
async fn main() {
    tracing_subscriber::fmt()
        .with_env_filter(
            env::var("RUST_LOG")
                .unwrap_or_else(|_| "plugin=info,tokio_tungstenite=warn".into()),
        )
        .init();

    let plugin_id = env::var("PLUGIN_ID").expect("PLUGIN_ID env var required");
    let token     = env::var("PLUGIN_TOKEN").expect("PLUGIN_TOKEN env var required");
    let ws_base   = env::var("IOT_AGENT_WS_URL").expect("IOT_AGENT_WS_URL env var required");

    let ws_base = ws_base.trim_end_matches('/');
    let ws_url  = format!("{ws_base}/websocket?token={token}");

    info!(plugin_id, "Plugin starting → {ws_base}/websocket");

    loop {
        match run_session(&plugin_id, &ws_url).await {
            Ok(()) => {
                info!(plugin_id, "Disconnected cleanly, reconnecting in 5 s");
                sleep(Duration::from_secs(5)).await;
            }
            Err(e) => {
                warn!(plugin_id, error = %e, "Session error, reconnecting in 10 s");
                sleep(Duration::from_secs(10)).await;
            }
        }
    }
}

// ---------------------------------------------------------------------------
// One connected session
// ---------------------------------------------------------------------------

async fn run_session(plugin_id: &str, ws_url: &str) -> Result<()> {
    let (ws, _resp) = connect_async(ws_url)
        .await
        .context("WebSocket connect failed")?;
    info!(plugin_id, "WebSocket connected");

    let (mut sink, mut stream) = ws.split();

    // -- Join plugin:{plugin_id} channel ----------------------------------
    let join_ref = next_ref();
    let topic    = format!("plugin:{plugin_id}");
    sink.send(phx_msg(Some(&join_ref), &join_ref, &topic, "phx_join", json!({})))
        .await
        .context("send phx_join")?;

    if !await_join_reply(&mut stream, &topic).await? {
        return Err(anyhow!("Channel join rejected by server"));
    }
    info!(plugin_id, "Joined channel {topic}");

    // -- Register entity type URI ----------------------------------------
    sink.send(phx_msg(
        None,
        &next_ref(),
        &topic,
        "register",
        json!({ "entity_type_uri": "WeatherObserved" }),
    ))
    .await
    .context("send register")?;
    info!(plugin_id, "Registered as WeatherObserved");

    // -- Create initial entity -------------------------------------------
    let mut sensor = Sensor::new();
    let eid = entity_id(plugin_id);
    let cr_ref = next_ref();
    sink.send(phx_msg(
        None,
        &cr_ref,
        &topic,
        "entity_create",
        json!({
            "request_id": cr_ref,
            "entity": build_entity(plugin_id, sensor.temp(), sensor.hum())
        }),
    ))
    .await
    .context("send entity_create")?;
    info!(
        plugin_id,
        entity_id = eid,
        temp = sensor.temp(),
        humidity = sensor.hum(),
        "Initial entity created"
    );

    // -- Event loop -------------------------------------------------------
    let mut update_tick = interval(Duration::from_secs(10));
    let mut hb_tick     = interval(Duration::from_secs(30));
    update_tick.tick().await; // skip the immediate first fire

    loop {
        tokio::select! {
            frame = stream.next() => {
                match frame {
                    Some(Ok(Message::Text(text))) => on_inbound(&text, plugin_id),
                    Some(Ok(Message::Close(_))) | None => {
                        info!(plugin_id, "Server closed connection");
                        return Ok(());
                    }
                    Some(Ok(_))  => {}
                    Some(Err(e)) => return Err(e.into()),
                }
            }

            _ = update_tick.tick() => {
                sensor.tick();
                let upd_ref = next_ref();
                sink.send(phx_msg(
                    None,
                    &upd_ref,
                    &topic,
                    "entity_update",
                    json!({
                        "request_id": upd_ref,
                        "entity_id":  eid,
                        "attrs":      build_update_attrs(sensor.temp(), sensor.hum())
                    }),
                ))
                .await
                .context("send entity_update")?;
                info!(plugin_id, temp = sensor.temp(), humidity = sensor.hum(), "Published update");
            }

            _ = hb_tick.tick() => {
                sink.send(phx_msg(None, &next_ref(), "phoenix", "heartbeat", json!({})))
                    .await
                    .context("send heartbeat")?;
                debug!(plugin_id, "Heartbeat sent");
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Wait for phx_reply confirming the channel join
// ---------------------------------------------------------------------------

async fn await_join_reply(
    stream: &mut (impl StreamExt<
        Item = Result<Message, tokio_tungstenite::tungstenite::Error>,
    > + Unpin),
    topic: &str,
) -> Result<bool> {
    while let Some(msg) = stream.next().await {
        let text = match msg? {
            Message::Text(t) => t,
            _ => continue,
        };
        let frame: Value = serde_json::from_str(&text).unwrap_or(Value::Null);
        if frame.get(2).and_then(Value::as_str) == Some(topic)
            && frame.get(3).and_then(Value::as_str) == Some("phx_reply")
        {
            let status = frame
                .get(4)
                .and_then(|p| p.get("status"))
                .and_then(Value::as_str)
                .unwrap_or("");
            return Ok(status == "ok");
        }
    }
    Err(anyhow!("Connection closed before join reply"))
}

// ---------------------------------------------------------------------------
// Handle server → plugin messages
// ---------------------------------------------------------------------------

fn on_inbound(text: &str, plugin_id: &str) {
    let Ok(frame) = serde_json::from_str::<Value>(text) else { return };
    let event   = frame.get(3).and_then(Value::as_str).unwrap_or("");
    let payload = frame.get(4).cloned().unwrap_or(Value::Null);

    match event {
        "entity_response" => {
            let status = payload.get("status").and_then(Value::as_str).unwrap_or("?");
            let req_id = payload.get("request_id").and_then(Value::as_str).unwrap_or("?");
            if status == "ok" {
                debug!(plugin_id, req_id, "entity_response ok");
            } else {
                warn!(plugin_id, req_id, ?payload, "entity_response non-ok");
            }
        }
        "entity_changed" => {
            let eid = payload.get("entity_id").and_then(Value::as_str).unwrap_or("?");
            info!(plugin_id, entity_id = eid, "entity_changed notification received");
        }
        "error" => {
            error!(plugin_id, ?payload, "Agent error");
        }
        "welcome" => {
            let pid = payload.get("plugin_id").and_then(Value::as_str).unwrap_or("?");
            info!(plugin_id, "Welcome from agent (server plugin_id = '{pid}')");
        }
        "phx_reply" | "phx_close" => {
            debug!(event, "Phoenix control");
        }
        _ => {
            debug!(plugin_id, event, "Unknown event");
        }
    }
}
