import Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :eos, EosWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "ZqvPDFZWqiczwQUD2C2l/biTZqtt0ijvtaj4jTjZ34kZ3H2+1moswrmbQ9k1I5w/",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:eos, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:eos, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :eos, EosWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$",
      # Gettext translations
      ~r"priv/gettext/.*\.po$",
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/eos_web/router\.ex$",
      ~r"lib/eos_web/(controllers|live|components)/.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :eos, dev_routes: true

# EOS dev defaults — override via environment variables or .envrc
config :eos,
  phaeton_url: System.get_env("PHAETON_URL", "http://localhost:4001"),
  phaeton_agent_token: System.get_env("PHAETON_AGENT_TOKEN", "dev_token"),
  agent_base_url: System.get_env("AGENT_BASE_URL", "http://localhost:4000"),
  agent_ws_url: System.get_env("AGENT_WS_URL", "ws://localhost:4000/plugins"),
  plugin_token_secret: System.get_env("PLUGIN_TOKEN_SECRET", "dev_plugin_secret_change_me"),
  k8s_namespace: System.get_env("K8S_NAMESPACE", "default"),
  k8s_conn: System.get_env("KUBECONFIG"),
  tenants:
    System.get_env("TENANTS", "default,ElHierro") |> String.split(",") |> Enum.map(&String.trim/1)

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
